segmentio_write_key:
  development: jbdukhri13
  staging: 830gbp5ux9
  production: rkt88i7k3w

dashboard_login_url: https://dashboard.aptible.com/login
dashboard_signup_url: /pricing/
production_signup_url: https://dashboard.aptible.com/signup?plan=production
development_signup_url: https://dashboard.aptible.com/signup?plan=development
status_url: http://status.aptible.com/

support_phone: (866) 296-5003
support_email: support@aptible.com
support_url: https://www.aptible.com/support/
sales_phone: (866) 296-5003
sales_email: sales@aptible.com
hello_email: hello@aptible.com
github: aptible
twitter: aptible
address_1: 1644 Platte St
city: Denver
state: CO
zip: 80202

blog_assets: '/blog/assets/'
page_assets: '/pages/assets/'
legal_assets: '/legal/assets/'
