dev:
  segmentio:
    write_key: jbdukhri13
    read_key: pj65hq5cnb

staging:
  segmentio:
    write_key: 830gbp5ux9
    read_key: t36trychr4

production:
  segmentio:
    write_key: rkt88i7k3w
    read_key: va76eltdon


knowledgebase_url: http://aptible.zendesk.com
knowledgebase_search_url: http://aptible.zendesk.com/hc/en-us/search
dashboard_login_url: http://dashboard.aptible.com/login
dashboard_signup_url: http://dashboard.aptible.com/signup
production_signup_url: http://dashboard.aptible.com/signup?plan=production
development_signup_url: http://dashboard.aptible.com/signup?plan=development

support_phone: (866) 296-5003
support_email: support@aptible.com
sales_phone: (866) 296-5003
sales_email: sales@aptible.com
hello_email: hello@aptible.com
github: aptible
twitter: aptible
address_1: 455 Mission Bay Blvd South
city: San Francisco
state: CA
zip: 94158

blog_assets: '/blog/assets/'
page_assets: '/pages/assets/'
legal_assets: '/legal/assets/'
